---
- hosts: all
  become: true
  tasks:
  - import_tasks: common-tasks.yml

  - name: Initialize the Kubernetes cluster using kubeadm
    command: "{{ item }}"
    args:
      creates: /tmp/.k8s_init
    with_items:
     - kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10"  --node-name k8s-master --pod-network-cidr=192.168.0.0/16
     - touch /tmp/.k8s_init


  - name: Setup kubeconfig for vagrant user
    command: "{{ item }}"
    with_items:
     - mkdir -p /home/vagrant/.kube
     - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
     - chown vagrant:vagrant /home/vagrant/.kube/config

  - name: Install calico pod network
    become: false
    command: "{{ item }}"
    args:
      creates: /tmp/.calico
    with_items:
     - kubectl create -f https://docs.projectcalico.org/v3.9/getting-started/kubernetes/installation/hosted/calico.yaml
     - touch /tmp/.calico  
    

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"


  handlers:
    - name: docker status
      service: name=docker state=started
