---
- hosts: all
  become: true
  tasks:    
  - name: "Make sure 127.0.0.1 is not mapped to {{ ansible_host }}"
    lineinfile:
      path: /etc/hosts
      state: absent
      regexp: '^127\.0\.1\.1\t{{ ansible_host }}\t{{ ansible_host }}'
  
  - import_tasks: common-tasks.yml

  - name: Initialize the Kubernetes cluster using kubeadm
    command: "{{ item }}"
    args:
      creates: /tmp/.k8s_init
    with_items:
     - kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10"  --node-name k8s-master --pod-network-cidr=172.16.0.0/16
     - touch /tmp/.k8s_init
     
#  - name: set api server proxy
#    shell: kubectl proxy --port=8080 &
#    args:
#      creates: /tmp/.api_proxy

  - name: Setup kubeconfig for vagrant user
    command: "{{ item }}"
    with_items:
     - mkdir -p /home/vagrant/.kube
     - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
     - chown vagrant:vagrant /home/vagrant/.kube/config

  - name: Install calico pod network
    become: false
    command: "{{ item }}"
    args:
      creates: /tmp/.calico
    with_items:
     - kubectl apply -f https://docs.projectcalico.org/v3.9/manifests/calico.yaml
     - touch /tmp/.calico  
    

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

  - name: create service account for helm
    become: false
    command: "{{ item }}"
    args:
      creates: /tmp/.helm_account
    with_items:
     - kubectl create serviceaccount -n kube-system tiller
     - kubectl create clusterrolebinding tiller-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
     - touch /tmp/.helm_account

  - name: Installation Helm v2.15
    unarchive:
      src: https://get.helm.sh/helm-v2.15.1-linux-amd64.tar.gz
      dest: /usr/local/bin
      extra_opts:
       - --strip=1
       - --wildcards
       - '*/helm'
      remote_src: yes

  - name: create service account for dashboard
    become: false
    command: "{{ item }}"
    args:
      creates: /tmp/.dashboard_account
    with_items:
     - kubectl create serviceaccount cluster-admin-dashboard-sa
     - kubectl create clusterrolebinding cluster-admin-dashboard-sa --clusterrole=cluster-admin --serviceaccount=default:cluster-admin-dashboard-sa
     - touch /tmp/.dashboard_account
       
  - name: Installation K8s Dashboard
    become: false
    command: '{{ item }}'
    args:
      creates: /tmp/.k8s_dashboard
    with_items:
     - kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta4/aio/deploy/recommended.yaml
     - touch /tmp/.k8s_dashboard
    
  - name: Helm In-Cluster Initialization
    become: false
    command: "{{ item }}"
    args:
      creates: /tmp/.init_helm
    with_items:  
     - helm init --service-account tiller
     - touch /tmp/.init_helm
      
  handlers:
    - name: docker status
      service: name=docker state=started
