---
- hosts: all
  become: true
  tasks:
  - import_tasks: common-tasks.yml

  - name: Copy the join command to server location
    copy: src=join-command dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    command: "{{ item }}"
    args:
      creates: /tmp/.join_cluster
    with_items:
     - sh /tmp/join-command.sh
     - touch /tmp/.calico

  handlers:
    - name: docker status
      service: name=docker state=started

