---
- hosts: all
  become: true
  tasks:
  - name: "Make sure 127.0.0.1 is not mapped to {{ ansible_host }}"
    lineinfile:
      path: /etc/hosts
      state: absent
      regexp: '^127\.0\.1\.1\t{{ ansible_host }}\t{{ ansible_host }}'
    
  - import_tasks: common-tasks.yml

  - name: Copy the join command to server location
    copy: src=join-command dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    command: "{{ item }}"
    args:
      creates: /tmp/.join_cluster
    with_items:
     - sh /tmp/join-command.sh
     - touch /tmp/.calico

  handlers:
    - name: docker status
      service: name=docker state=started

