apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifactory-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 22Gi
  accessModes:
  - ReadWriteOnce
  local:
    path: /mnt/data/artifactory
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-1
          - node-2
