apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgresql
  name: data-artifactory-postgresql-0
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
